export const ADD_PRODUCT_TO_FAVORITES = "ADD_PRODUCT_TO_FAVORITES";
export const ADD_PRODUCT_TO_FAVORITES_ERROR = "ADD_PRODUCT_TO_FAVORITES_ERROR";
export const REMOVE_PRODUCT_TO_FAVORITES = "REMOVE_PRODUCT_TO_FAVORITES";
export const REMOVE_PRODUCT_TO_FAVORITES_ERROR =
  "REMOVE_PRODUCT_TO_FAVORITES_ERROR";
export const REMOVE_PRODUCT_FROM_FAVORITES = "REMOVE_PRODUCT_FROM_FAVORITES";
export const REMOVE_PRODUCT_FROM_FAVORITES_ERROR =
  "REMOVE_PRODUCT_FROM_FAVORITES_ERROR";
export const ADD_PRODUCT_RATING_REQUEST = "ADD_PRODUCT_RATING_REQUEST";
export const ADD_PRODUCT_RATING_SUCCESS = "ADD_PRODUCT_RATING_SUCCESS";
export const ADD_PRODUCT_RATING_FAIL = "ADD_PRODUCT_RATING_FAIL";
