export const ADD_PRODUCT_TO_FAVORITES = "ADD_PRODUCT_TO_FAVORITES";
export const ADD_PRODUCT_TO_FAVORITES_ERROR = "ADD_PRODUCT_TO_FAVORITES_ERROR";
export const REMOVE_PRODUCT_TO_FAVORITES = "REMOVE_PRODUCT_TO_FAVORITES";
export const REMOVE_PRODUCT_TO_FAVORITES_ERROR =
  "REMOVE_PRODUCT_TO_FAVORITES_ERROR";
export const REMOVE_PRODUCT_FROM_FAVORITES = "REMOVE_PRODUCT_FROM_FAVORITES";
export const REMOVE_PRODUCT_FROM_FAVORITES_ERROR =
  "REMOVE_PRODUCT_FROM_FAVORITES_ERROR";
