export const ADD_INCREMENT_CLICKS = "ADD_INCREMENT_CLICKS";
export const ADD_INCREMENT_CLICKS_ERROR = "ADD_INCREMENT_CLICKS_ERROR";
export const ADD_INCREMENT_CLICKS_REQUEST = "ADD_INCREMENT_CLICKS_REQUEST";
export const ADD_INCREMENT_CLICKS_SUCCESS = "ADD_INCREMENT_CLICKS_SUCCESS";
export const ADD_INCREMENT_CLICKS_FAIL = "ADD_INCREMENT_CLICKS_FAIL";
