export const GET_RECOMMENDATIONS_REQUEST = "GET_RECOMMENDATIONS_REQUEST";
export const GET_RECOMMENDATIONS_SUCCESS = "GET_RECOMMENDATIONS_SUCCESS";
export const GET_RECOMMENDATIONS_FAILURE = "GET_RECOMMENDATIONS_FAILURE";
export const GET_RECOMMENDATIONS_ERROR = "GET_RECOMMENDATIONS_ERROR";
export const GET_RECOMMENDATIONS_RESET = "GET_RECOMMENDATIONS_RESET";
